import { defineWorkflow } from "@/lib/workflows/types";

// KYC Review — the first substantial workflow, exercising queues, assignment,
// escalation, role-based approvals and audit.
// Safeguard: high-risk cases can only be approved by a supervisor
// (enforced via the amountThreshold guard on riskScore).

export const kycReview = defineWorkflow({
  slug: "kyc-review",
  name: "KYC Review",
  description: "Review and decision customer KYC cases.",
  icon: "ShieldCheck",
  recordNoun: "case",
  visibleToRoles: ["analyst", "supervisor", "ops_admin", "eng_admin"],
  titleField: "customerName",
  fields: [
    { key: "customerName", label: "Customer", type: "text", required: true },
    {
      key: "customerType",
      label: "Customer Type",
      type: "select",
      options: ["Individual", "Business"],
      required: true,
    },
    { key: "jurisdiction", label: "Jurisdiction", type: "select", options: ["US", "UK", "EU", "CA", "SG", "BR", "MX"], required: true },
    { key: "submittedAt", label: "Submitted", type: "date", required: true },
    { key: "riskScore", label: "Risk Score", type: "number", required: true },
    {
      key: "riskLevel",
      label: "Risk Level",
      type: "select",
      options: ["Low", "Medium", "High"],
      required: true,
    },
    {
      key: "flaggedReasons",
      label: "Flagged Reasons",
      type: "multiSelect",
      options: [
        "Sanctions list partial match",
        "Document mismatch",
        "High-risk jurisdiction",
        "PEP indicator",
        "Velocity anomaly",
        "Address verification failed",
      ],
    },
    {
      key: "verificationSignals",
      label: "Verification Signals",
      type: "longText",
    },
    { key: "notes", label: "Analyst Notes", type: "longText", editable: true },
  ],
  statuses: [
    { key: "pending", label: "Pending Review", color: "gray" },
    { key: "in_review", label: "In Review", color: "blue" },
    { key: "additional_review", label: "Additional Review", color: "yellow" },
    { key: "escalated", label: "Escalated", color: "orange" },
    { key: "approved", label: "Approved", color: "green", terminal: true },
    { key: "rejected", label: "Rejected", color: "red", terminal: true },
  ],
  initialStatus: "pending",
  actions: [
    {
      key: "assign_to_me",
      label: "Assign to Me",
      fromStatuses: ["pending", "additional_review"],
      toStatus: "in_review",
      roles: ["analyst", "supervisor"],
      assignToActor: true,
    },
    {
      key: "request_additional_review",
      label: "Request Additional Review",
      fromStatuses: ["in_review", "escalated"],
      toStatus: "additional_review",
      roles: ["analyst", "supervisor"],
      requiredInputs: [
        { key: "reason", label: "What additional review is needed?", type: "longText" },
      ],
      clearAssignee: true,
    },
    {
      key: "escalate",
      label: "Escalate",
      fromStatuses: ["in_review", "additional_review"],
      toStatus: "escalated",
      roles: ["analyst", "supervisor"],
      confirm: true,
      confirmMessage: "Escalate this case to a supervisor?",
      requiredInputs: [{ key: "reason", label: "Escalation reason", type: "longText" }],
      variant: "default",
    },
    {
      key: "approve",
      label: "Approve",
      fromStatuses: ["in_review", "escalated", "additional_review"],
      toStatus: "approved",
      roles: ["analyst", "supervisor"],
      confirm: true,
      confirmMessage: "Approve this KYC case? The decision is recorded with the KYC vendor.",
      variant: "primary",
      guards: [
        {
          type: "amountThreshold",
          field: "riskScore",
          threshold: 70,
          requiredRoles: ["supervisor"],
          message: "High-risk cases (risk score ≥ 70) require supervisor approval.",
        },
      ],
      integration: "kyc-provider",
    },
    {
      key: "reject",
      label: "Reject",
      fromStatuses: ["in_review", "escalated", "additional_review"],
      toStatus: "rejected",
      roles: ["analyst", "supervisor"],
      confirm: true,
      confirmMessage: "Reject this KYC case?",
      requiredInputs: [{ key: "reason", label: "Rejection reason", type: "longText" }],
      variant: "destructive",
      guards: [
        {
          type: "amountThreshold",
          field: "riskScore",
          threshold: 70,
          requiredRoles: ["supervisor"],
          message: "High-risk cases (risk score ≥ 70) require a supervisor decision.",
        },
      ],
      integration: "kyc-provider",
    },
  ],
  views: [
    { key: "all", label: "All Cases", filter: {} },
    { key: "unassigned", label: "Unassigned", filter: { unassigned: true, statuses: ["pending", "additional_review"] } },
    { key: "mine", label: "Assigned to Me", filter: { assignedToMe: true } },
    { key: "high_risk", label: "High Risk", filter: { fieldEquals: { riskLevel: "High" } } },
    { key: "escalated", label: "Escalated", filter: { statuses: ["escalated"] } },
    { key: "pending", label: "Pending Review", filter: { statuses: ["pending", "in_review", "additional_review"] } },
    { key: "completed", label: "Recently Completed", filter: { statuses: ["approved", "rejected"] } },
  ],
  tableColumns: ["customerName", "customerType", "jurisdiction", "riskScore", "riskLevel", "submittedAt"],
  dashboardCards: [
    { type: "recordCount", label: "Open Cases", statuses: ["pending", "in_review", "additional_review", "escalated"] },
    { type: "statusCount", label: "Escalated", statuses: ["escalated"] },
    { type: "statusCount", label: "Approved", statuses: ["approved"] },
    { type: "statusCount", label: "Rejected", statuses: ["rejected"] },
  ],
});
