import { defineWorkflow } from "@/lib/workflows/types";

// Refunds — reuses the exact primitives built for KYC (queue, detail view,
// actions, guards, audit) plus dashboard cards.
// Safeguard: refunds at or above the configurable "refund.approvalThreshold"
// platform setting require a supervisor (see PlatformSetting seed).

export const refunds = defineWorkflow({
  slug: "refunds",
  name: "Refunds",
  description: "Review, approve, and issue customer refunds.",
  icon: "Banknote",
  recordNoun: "refund",
  visibleToRoles: ["analyst", "supervisor", "ops_admin", "eng_admin"],
  titleField: "customerName",
  showDashboard: true,
  fields: [
    { key: "refundId", label: "Refund ID", type: "text", required: true },
    { key: "paymentId", label: "Payment ID", type: "text", required: true },
    { key: "customerName", label: "Customer", type: "text", required: true },
    { key: "amount", label: "Amount", type: "money", required: true, currencyField: "currency" },
    { key: "currency", label: "Currency", type: "select", options: ["USD", "EUR", "GBP"], required: true },
    {
      key: "reason",
      label: "Refund Reason",
      type: "select",
      options: [
        "Duplicate charge",
        "Service not delivered",
        "Fraudulent transaction",
        "Customer dispute",
        "Billing error",
        "Goodwill",
      ],
      required: true,
    },
    { key: "requestedAt", label: "Requested", type: "date", required: true },
    { key: "requestedBy", label: "Requested By", type: "text", required: true },
    { key: "notes", label: "Notes", type: "longText", editable: true },
  ],
  statuses: [
    { key: "pending", label: "Pending", color: "gray" },
    { key: "in_review", label: "In Review", color: "blue" },
    { key: "info_requested", label: "Info Requested", color: "yellow" },
    { key: "escalated", label: "Escalated", color: "orange" },
    { key: "approved", label: "Approved", color: "green", terminal: true },
    { key: "rejected", label: "Rejected", color: "red", terminal: true },
  ],
  initialStatus: "pending",
  actions: [
    {
      key: "assign_to_me",
      label: "Assign to Me",
      fromStatuses: ["pending", "info_requested"],
      toStatus: "in_review",
      roles: ["analyst", "supervisor"],
      assignToActor: true,
    },
    {
      key: "request_information",
      label: "Request Information",
      fromStatuses: ["in_review", "escalated"],
      toStatus: "info_requested",
      roles: ["analyst", "supervisor"],
      requiredInputs: [{ key: "request", label: "Information needed", type: "longText" }],
    },
    {
      key: "escalate",
      label: "Escalate",
      fromStatuses: ["in_review", "info_requested"],
      toStatus: "escalated",
      roles: ["analyst", "supervisor"],
      confirm: true,
      confirmMessage: "Escalate this refund to a supervisor?",
      requiredInputs: [{ key: "reason", label: "Escalation reason", type: "longText" }],
    },
    {
      key: "approve",
      label: "Approve Refund",
      fromStatuses: ["in_review", "escalated", "info_requested"],
      toStatus: "approved",
      roles: ["analyst", "supervisor"],
      confirm: true,
      confirmMessage: "Approve and issue this refund via the payment provider?",
      variant: "primary",
      guards: [
        {
          type: "amountThreshold",
          field: "amount",
          thresholdSettingKey: "refund.approvalThreshold",
          requiredRoles: ["supervisor"],
          message: "Refunds at or above the configured threshold require supervisor approval.",
        },
      ],
      integration: "refund-provider",
    },
    {
      key: "reject",
      label: "Reject",
      fromStatuses: ["in_review", "escalated", "info_requested"],
      toStatus: "rejected",
      roles: ["analyst", "supervisor"],
      confirm: true,
      confirmMessage: "Reject this refund request?",
      requiredInputs: [{ key: "reason", label: "Rejection reason", type: "longText" }],
      variant: "destructive",
    },
  ],
  views: [
    { key: "all", label: "All Refunds", filter: {} },
    { key: "pending", label: "Pending", filter: { statuses: ["pending", "in_review", "info_requested"] } },
    { key: "mine", label: "Assigned to Me", filter: { assignedToMe: true } },
    { key: "escalated", label: "Escalated", filter: { statuses: ["escalated"] } },
    { key: "completed", label: "Completed", filter: { statuses: ["approved", "rejected"] } },
  ],
  tableColumns: ["refundId", "customerName", "amount", "reason", "requestedAt", "requestedBy"],
  dashboardCards: [
    { type: "recordCount", label: "Pending Refunds", statuses: ["pending", "in_review", "info_requested"] },
    { type: "moneySum", label: "Approved Amount", field: "amount", statuses: ["approved"] },
    { type: "moneySum", label: "Pending Amount", field: "amount", statuses: ["pending", "in_review", "info_requested", "escalated"] },
    { type: "statusCount", label: "Escalated", statuses: ["escalated"] },
  ],
});
