import { defineWorkflow } from "../../src/lib/workflows/types";

// Chargeback Review — created with the Workflow Builder and seeded as a
// PUBLISHED builder-defined workflow. Every part of it (fields, states,
// actions, comparison rules, views, sort, search) is expressible through the
// guided wizard: it demonstrates that a new fintech workflow can be assembled
// from platform primitives without code.

export const chargebackReviewDefinition = defineWorkflow({
  slug: "chargeback-review",
  name: "Chargeback Review",
  description: "Review and resolve customer chargeback cases.",
  icon: "CreditCard",
  recordNoun: "chargeback",
  recordNounPlural: "chargebacks",
  category: "Disputes",
  visibleToRoles: ["analyst", "supervisor", "ops_admin", "eng_admin"],
  titleField: "chargebackId",
  fields: [
    { key: "chargebackId", label: "Chargeback ID", type: "text", required: true },
    { key: "customerName", label: "Customer", type: "text", required: true },
    { key: "merchantName", label: "Merchant", type: "text", required: true },
    { key: "amount", label: "Amount", type: "money", required: true, currencyField: "currency" },
    {
      key: "currency",
      label: "Currency",
      type: "select",
      options: ["USD", "EUR", "GBP"],
      required: true,
      defaultValue: "USD",
      showInDetail: true,
    },
    {
      key: "reason",
      label: "Reason",
      type: "select",
      options: [
        "Fraudulent transaction",
        "Product not received",
        "Product unacceptable",
        "Duplicate processing",
        "Credit not processed",
      ],
      required: true,
    },
    { key: "submittedAt", label: "Submitted Date", type: "date", required: true },
    {
      key: "riskLevel",
      label: "Risk Level",
      type: "select",
      options: ["Low", "Medium", "High"],
      required: true,
      defaultValue: "Low",
    },
    { key: "notes", label: "Notes", type: "longText", editable: true },
  ],
  statuses: [
    { key: "new", label: "New", color: "gray" },
    { key: "inReview", label: "In Review", color: "blue" },
    { key: "escalated", label: "Escalated", color: "orange" },
    { key: "approved", label: "Approved", color: "green", terminal: true },
    { key: "rejected", label: "Rejected", color: "red", terminal: true },
  ],
  initialStatus: "new",
  actions: [
    {
      key: "startReview",
      label: "Start Review",
      fromStatuses: ["new"],
      toStatus: "inReview",
      roles: ["analyst", "supervisor"],
      assignToActor: true,
    },
    {
      key: "escalate",
      label: "Escalate",
      fromStatuses: ["inReview"],
      toStatus: "escalated",
      roles: ["analyst", "supervisor"],
      requiredInputs: [{ key: "reason", label: "Escalation reason", type: "longText" }],
    },
    {
      key: "approve",
      label: "Approve Chargeback",
      fromStatuses: ["inReview", "escalated"],
      toStatus: "approved",
      roles: ["analyst", "supervisor"],
      confirm: true,
      confirmMessage: "Approve this chargeback and refund the customer?",
      variant: "primary",
      guards: [
        {
          type: "rule",
          field: "amount",
          operator: "greaterThan",
          value: 5000,
          requiredRoles: ["supervisor"],
          message: "Chargebacks over $5,000 require Supervisor approval.",
        },
        {
          type: "rule",
          field: "riskLevel",
          operator: "equals",
          value: "High",
          requiredRoles: ["supervisor"],
          message: "High-risk chargebacks require Supervisor approval.",
        },
      ],
    },
    {
      key: "reject",
      label: "Reject Chargeback",
      fromStatuses: ["inReview", "escalated"],
      toStatus: "rejected",
      roles: ["supervisor"],
      confirm: true,
      confirmMessage: "Reject this chargeback? The merchant will be notified.",
      variant: "destructive",
      requiredInputs: [{ key: "reason", label: "Rejection reason", type: "longText" }],
    },
  ],
  views: [
    { key: "all", label: "All", filter: {} },
    { key: "unassigned", label: "Unassigned", filter: { unassigned: true } },
    { key: "mine", label: "Assigned to Me", filter: { assignedToMe: true } },
    { key: "new", label: "New", filter: { statuses: ["new"] } },
    { key: "inReview", label: "In Review", filter: { statuses: ["inReview"] } },
    { key: "escalated", label: "Escalated", filter: { statuses: ["escalated"] } },
  ],
  tableColumns: ["chargebackId", "customerName", "merchantName", "amount", "riskLevel", "submittedAt"],
  defaultSort: { field: "submittedAt", direction: "desc" },
  searchableFields: ["chargebackId", "customerName", "merchantName"],
  dashboardCards: [
    { type: "recordCount", label: "Open Chargebacks", statuses: ["new", "inReview", "escalated"] },
    { type: "moneySum", label: "Disputed Amount", field: "amount", statuses: ["new", "inReview", "escalated"] },
  ],
});
